### ISSUE TITLE
Issue with numpy

### ISSUE THREAD

**Issue by CosiMichele** [emmanuelgonz/collect_gps#1]
Issue with running the container either with docker and singularity on the UA HPC and personal computer.

Error is:
```
Traceback (most recent call last):
  File "/opt/img_coords_b2t_up.py", line 13, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.6/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/lib/python3.6/dist-packages/pandas/compat/numpy/__init__.py", line 21, in <module>
    "this version of pandas is incompatible with numpy < 1.15.4\n"
ImportError: this version of pandas is incompatible with numpy < 1.15.4
your numpy version is 1.13.3.
Please upgrade numpy to >= 1.15.4 to use this pandas version

```

However, it runs on YOUR interactive node, although we run the same code calling for the interactive node.

**Comment by CosiMichele** [comment]
Commands are:
`sudo docker run emmanuelgonzalez/collect_gps`
or
```
singularity run /xdisk/ericlyons/big_data/singularity_images/collect_gps.simg
singularity run docker://emmanuelgonzalez/collect_gps:latest
singularity run -B $(pwd):/mnt --pwd /mnt docker://emmanuelgonzalez/collect_gps:latest
```

and singularity versions are 3.6.0 or 3.2.1.

**Comment by emmanuelgonz** [comment]
Hi Michele, 

Thank you for posting your issue. I have changed the numpy version from 1.13.3 to 1.19.1 within the Dockerfile. Can you please let me know if this solved the issue?

**Comment by CosiMichele** [comment]
Seems like the updated container is working. Tested on both my personal machine and an HPC interactive node. 

Should run with either 
```
singularity run /xdisk/ericlyons/big_data/singularity_images/collect_gps.simg
singularity run -B $(pwd):/mnt --pwd /mnt docker://emmanuelgonzalez/collect_gps:latest
```

Thanks!
